[project]
name = "achievementsGetter"
version = "0.1.0"
description = "Get the achievements from the Google Sheet"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.4",
]
